const hotels = [
  {
    id: "1",
    cityName: "Mumbai",
    stateName: "Maharashtra",
    managerName: "Ravi Patel",
    companyName: "Luxury Stays",
    image: "https://example.com/images/hotel1.jpg",
  },
  {
    id: "2",
    cityName: "New Delhi",
    stateName: "Delhi",
    managerName: "Anita Sharma",
    companyName: "Elite Hotels",
    image: "https://example.com/images/hotel2.jpg",
  },
  {
    id: "3",
    cityName: "Bengaluru",
    stateName: "Karnataka",
    managerName: "Sanjay Kumar",
    companyName: "Urban Retreat",
    image: "https://example.com/images/hotel3.jpg",
  },
  {
    id: "4",
    cityName: "Chennai",
    stateName: "Tamil Nadu",
    managerName: "Priya Reddy",
    companyName: "Coastal Escape",
    image: "https://example.com/images/hotel4.jpg",
  },
  {
    id: "5",
    cityName: "Hyderabad",
    stateName: "Telangana",
    managerName: "Amit Desai",
    companyName: "Royal Suites",
    image: "https://example.com/images/hotel5.jpg",
  },
  {
    id: "6",
    cityName: "Kolkata",
    stateName: "West Bengal",
    managerName: "Meena Bhattacharya",
    companyName: "Grand Heritage",
    image: "https://example.com/images/hotel6.jpg",
  },
  {
    id: "7",
    cityName: "Pune",
    stateName: "Maharashtra",
    managerName: "Vikram Singh",
    companyName: "Tranquil Haven",
    image: "https://example.com/images/hotel7.jpg",
  },
  {
    id: "8",
    cityName: "Jaipur",
    stateName: "Rajasthan",
    managerName: "Rani Mehta",
    companyName: "Palace Inn",
    image: "https://example.com/images/hotel8.jpg",
  },
  {
    id: "9",
    cityName: "Agra",
    stateName: "Uttar Pradesh",
    managerName: "Rajesh Gupta",
    companyName: "Taj View",
    image: "https://example.com/images/hotel9.jpg",
  },
  {
    id: "10",
    cityName: "Udaipur",
    stateName: "Rajasthan",
    managerName: "Naina Singh",
    companyName: "Lake Palace",
    image: "https://example.com/images/hotel10.jpg",
  },
  {
    id: "11",
    cityName: "Ahmedabad",
    stateName: "Gujarat",
    managerName: "Rohit Shah",
    companyName: "Gujarat Grand",
    image: "https://example.com/images/hotel11.jpg",
  },
  {
    id: "12",
    cityName: "Surat",
    stateName: "Gujarat",
    managerName: "Sneha Patel",
    companyName: "Diamond Palace",
    image: "https://example.com/images/hotel12.jpg",
  },
  {
    id: "13",
    cityName: "Kanpur",
    stateName: "Uttar Pradesh",
    managerName: "Karan Yadav",
    companyName: "Kanpur Comfort",
    image: "https://example.com/images/hotel13.jpg",
  },
  {
    id: "14",
    cityName: "Indore",
    stateName: "Madhya Pradesh",
    managerName: "Pooja Sharma",
    companyName: "Central Oasis",
    image: "https://example.com/images/hotel14.jpg",
  },
  {
    id: "15",
    cityName: "Bhopal",
    stateName: "Madhya Pradesh",
    managerName: "Amit Malhotra",
    companyName: "Bhopal Bliss",
    image: "https://example.com/images/hotel15.jpg",
  },
  {
    id: "16",
    cityName: "Patna",
    stateName: "Bihar",
    managerName: "Suresh Kumar",
    companyName: "Patna Paradise",
    image: "https://example.com/images/hotel16.jpg",
  },
  {
    id: "17",
    cityName: "Lucknow",
    stateName: "Uttar Pradesh",
    managerName: "Rita Singh",
    companyName: "Royal Lucknow",
    image: "https://example.com/images/hotel17.jpg",
  },
  {
    id: "18",
    cityName: "Ranchi",
    stateName: "Jharkhand",
    managerName: "Amitabh Jain",
    companyName: "Ranchi Retreat",
    image: "https://example.com/images/hotel18.jpg",
  },
  {
    id: "19",
    cityName: "Jamshedpur",
    stateName: "Jharkhand",
    managerName: "Sonia Agarwal",
    companyName: "Steel City Inn",
    image: "https://example.com/images/hotel19.jpg",
  },
  {
    id: "20",
    cityName: "Chandigarh",
    stateName: "Chandigarh",
    managerName: "Neeraj Arora",
    companyName: "Chandigarh Charm",
    image: "https://example.com/images/hotel20.jpg",
  },
  {
    id: "21",
    cityName: "Shimla",
    stateName: "Himachal Pradesh",
    managerName: "Sushma Sharma",
    companyName: "Himalayan Haven",
    image: "https://example.com/images/hotel21.jpg",
  },
  {
    id: "22",
    cityName: "Manali",
    stateName: "Himachal Pradesh",
    managerName: "Ramesh Mehta",
    companyName: "Manali Magic",
    image: "https://example.com/images/hotel22.jpg",
  },
  {
    id: "23",
    cityName: "Dehradun",
    stateName: "Uttarakhand",
    managerName: "Sanjana Joshi",
    companyName: "Dehradun Delight",
    image: "https://example.com/images/hotel23.jpg",
  },
  {
    id: "24",
    cityName: "Haridwar",
    stateName: "Uttarakhand",
    managerName: "Raj Kumar",
    companyName: "Ganges View",
    image: "https://example.com/images/hotel24.jpg",
  },
  {
    id: "25",
    cityName: "Jaipur",
    stateName: "Rajasthan",
    managerName: "Priti Agarwal",
    companyName: "Rajasthan Rapture",
    image: "https://example.com/images/hotel25.jpg",
  },
  {
    id: "26",
    cityName: "Gurgaon",
    stateName: "Haryana",
    managerName: "Amit Sinha",
    companyName: "Gurgaon Grand",
    image: "https://example.com/images/hotel26.jpg",
  },
  {
    id: "27",
    cityName: "Noida",
    stateName: "Uttar Pradesh",
    managerName: "Ruchi Sharma",
    companyName: "Noida Nest",
    image: "https://example.com/images/hotel27.jpg",
  },
  {
    id: "28",
    cityName: "Meerut",
    stateName: "Uttar Pradesh",
    managerName: "Vikas Gupta",
    companyName: "Meerut Meadows",
    image: "https://example.com/images/hotel28.jpg",
  },
  {
    id: "29",
    cityName: "Mangalore",
    stateName: "Karnataka",
    managerName: "Swati Rao",
    companyName: "Coastal Charm",
    image: "https://example.com/images/hotel29.jpg",
  },
  {
    id: "30",
    cityName: "Coimbatore",
    stateName: "Tamil Nadu",
    managerName: "Arun Raj",
    companyName: "Coimbatore Comfort",
    image: "https://example.com/images/hotel30.jpg",
  },
];

export default hotels;
